# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript
steps:
  - task: NodeTool@0
    displayName: 'Use Node 10.x'
    inputs:
      versionSpec: 10.x

  - bash: |  
      set -ex

      # clean install
      npm ci
      npm run build

      mkdir -p linux
      cp build/* linux/

      npm run build-lib

      npm-cli-login
      npm version patch
      npm publish
    displayName: Build and publish

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: linux'
    inputs:
      PathtoPublish: linux
      ArtifactName: linux
